version: "3.8"

services:
    web:
        container_name: edufund-test_api
        build: .
        environment: 
            SERVER_ADDRESS: 127.0.0.1
            SERVER_PORT: 80
            REDIS_HOST: 127.0.0.1
            REDIS_DB: 0
            REDIS_PORT: 6379
            REDIS_PASSWORD: 
        ports:
        - "8080"
        volumes:
        - ./app
        links:
        - db
    db:
        container_name: edufund-test_db
        image: redis
        ports:
        - "6379"